import type { DraftRuleStep } from "../types/room.js";

export const defaultDraftRules: DraftRuleStep[] = [
  { side: "blue", action: "BAN", count: 1 },
  { side: "red", action: "BAN", count: 1 },
  { side: "blue", action: "PICK", count: 1 },
  { side: "red", action: "PICK", count: 2 },
  { side: "blue", action: "PICK", count: 2 },
  { side: "red", action: "PICK", count: 1 },
  { side: "red", action: "BAN", count: 1 },
  { side: "blue", action: "BAN", count: 1 },
  { side: "red", action: "PICK", count: 1 },
  { side: "blue", action: "PICK", count: 2 },
  { side: "red", action: "PICK", count: 2 },
  { side: "blue", action: "PICK", count: 1 },
];

export const defaultHeroes = [
  "Abrams",
  "Apollo",
  "Bebop",
  "Billy",
  "Calico",
  "Celeste",
  "Drifter",
  "Dynamo",
  "Graves",
  "Grey Talon",
  "Haze",
  "Holliday",
  "Inferno",
  "Ivy",
  "Kelvin",
  "Lady Geist",
  "Lash",
  "McGinnis",
  "Mina",
  "Mirage",
  "Mo & Krill",
  "Paige",
  "Paradox",
  "Pocket",
  "Rem",
  "Seven",
  "Shiv",
  "Silver",
  "Sinclair",
  "The Doorman",
  "Venator",
  "Victor",
  "Vindicta",
  "Viscous",
  "Vyper",
  "Warden",
  "Wraith",
  "Yamato",
];
